name: NceaBot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allow workflow to push tags and create releases
  issues: read

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all files are fetched

      - name: Debug File Structure
        run: |
          echo "Current Directory: $(pwd)"
          ls -R  # List all files recursively to confirm presence of main.py

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller kivy selenium webdriver-manager google-generativeai
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name NceaBot main.py  # Adjust if needed

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: NceaBot-MacOS
          path: dist/NceaBot  # Corrected path to match PyInstaller output

      - name: Create GitHub Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          TAG="v${{ github.run_number }}"
          
          # Check if the tag exists before deleting
          if git show-ref --tags --quiet --verify -- "refs/tags/$TAG"; then
            git tag -d "$TAG"
            git push --delete origin "$TAG"
          fi
          
          # Create and push the new tag
          git tag -a "$TAG" -m "Release version $TAG"
          git push origin "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release and Upload App
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release v${{ github.run_number }}"
          files: dist/NceaBot  # Corrected path for release upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
