# This workflow will build your NCEA Bot application as an executable
name: NceaBot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      with:
        fetch-depth: 0  # Ensures all files are fetched
    - name: Debug File Structure
      run: |
        echo "Current Directory: $(pwd)"
        ls -R  # List all files recursively to confirm the presence of main.py
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        brew install xquartz
        python -m pip install --upgrade pip
        pip install pyinstaller kivy selenium webdriver-manager google-generativeai
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build with PyInstaller
      run: |
        # If your main.py is inside a folder, change `main.py` to the correct path
        pyinstaller --onefile --windowed --name NceaBot main.py  # Make sure this is the correct path
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: NceaBot-MacOS
        path: dist/NceaBot
