name: NceaBot

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
permissions:
  contents: write
  issues: read

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Debug File Structure
        run: |
          echo "Current Directory: $(pwd)"
          ls -R
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          brew install xquartz
          python -m pip install --upgrade pip
          pip install pyinstaller kivy selenium webdriver-manager google-generativeai
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Build macOS App
        run: |
          pyinstaller --windowed --onefile --name NceaBot main.py
      
      - name: Set executable permissions
        run: chmod +x dist/NceaBot.app/Contents/MacOS/NceaBot
      
      - name: Zip the macOS App
        run: zip -r NceaBot-MacOS.zip dist/NceaBot.app
      
      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: NceaBot-MacOS
          path: NceaBot-MacOS.zip
      
      - name: Create GitHub Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          TAG_NAME="v${{ github.run_number }}"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            git tag -d "$TAG_NAME"
            git push --delete origin "$TAG_NAME"
          fi
          git tag -a "$TAG_NAME" -m "Release version $TAG_NAME"
          git push origin "$TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create GitHub Release and Upload App
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Release v${{ github.run_number }}"
          files: NceaBot-MacOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

