name: NceaBot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest  # Use Windows runner for building the .exe

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      with:
        fetch-depth: 0  # Ensures all files are fetched
    
    - name: Debug File Structure
      run: |
        echo "Current Directory: $(pwd)"
        dir  # List all files in the current directory to confirm the presence of main.py
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx_Freeze kivy selenium webdriver-manager google-generativeai
        if (Test-Path "requirements.txt") { pip install -r requirements.txt }
    
    - name: Build with cx_Freeze
      run: |
        # Create the .exe file using cx_Freeze directly in the workflow
        python -m cx_Freeze main.py --target-dir build/exe

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: NceaBot-Windows
        path: build/exe/NceaBot.exe  # Path to the generated .exe file from cx_Freeze

