name: NceaBot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Debug File Structure
      run: |
        echo "Current Directory: $(pwd)"
        ls -R
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        brew install xquartz
        python -m pip install --upgrade pip
        pip install pyinstaller kivy selenium webdriver-manager google-generativeai
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name NceaBot main.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: NceaBot-MacOS
        path: dist/NceaBot
    
    - name: Create GitHub Tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        if git rev-parse "v${{ github.run_number }}" >/dev/null 2>&1; then
          git tag -d "v${{ github.run_number }}"
          git push --delete origin "v${{ github.run_number }}"
        fi
        git tag -a "v${{ github.run_number }}" -m "Release version ${{ github.run_number }}"
        git push origin "v${{ github.run_number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create GitHub Release and Upload App
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ github.run_number }}"
        name: "Release v${{ github.run_number }}"
        files: dist/NceaBot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
